# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'idle_start_display.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IdleStartDisplay(object):
    def setupUi(self, IdleStartDisplay):
        IdleStartDisplay.setObjectName("IdleStartDisplay")
        IdleStartDisplay.resize(800, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("DARTS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        IdleStartDisplay.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(IdleStartDisplay)
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(300, 200, 200, 100))
        self.startButton.setObjectName("startButton")
        self.helpButton = QtWidgets.QPushButton(self.centralwidget)
        self.helpButton.setGeometry(QtCore.QRect(10, 370, 75, 25))
        self.helpButton.setObjectName("helpButton")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(0, 60, 800, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        IdleStartDisplay.setCentralWidget(self.centralwidget)

        self.retranslateUi(IdleStartDisplay)
        QtCore.QMetaObject.connectSlotsByName(IdleStartDisplay)

    def retranslateUi(self, IdleStartDisplay):
        _translate = QtCore.QCoreApplication.translate
        IdleStartDisplay.setWindowTitle(_translate("IdleStartDisplay", "DARTS"))
        self.startButton.setText(_translate("IdleStartDisplay", "Start"))
        self.helpButton.setText(_translate("IdleStartDisplay", "Help"))
        self.titleLabel.setText(_translate("IdleStartDisplay", "Digital Accuracy Real-time Tracking and Scoring"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IdleStartDisplay = QtWidgets.QMainWindow()
    ui = Ui_IdleStartDisplay()
    ui.setupUi(IdleStartDisplay)
    IdleStartDisplay.show()
    sys.exit(app.exec_())
