# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_players_display.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectPlayersDisplay(object):
    def setupUi(self, SelectPlayersDisplay):
        SelectPlayersDisplay.setObjectName("SelectPlayersDisplay")
        SelectPlayersDisplay.resize(800, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("DARTS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SelectPlayersDisplay.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(SelectPlayersDisplay)
        self.centralwidget.setObjectName("centralwidget")
        self.helpButton = QtWidgets.QPushButton(self.centralwidget)
        self.helpButton.setGeometry(QtCore.QRect(10, 370, 75, 25))
        self.helpButton.setObjectName("helpButton")
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setGeometry(QtCore.QRect(150, 220, 200, 100))
        self.loadButton.setObjectName("loadButton")
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setGeometry(QtCore.QRect(715, 370, 75, 25))
        self.cancelButton.setObjectName("cancelButton")
        self.usernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.usernameLabel.setGeometry(QtCore.QRect(180, 140, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setObjectName("usernameLabel")
        self.usernameInput = QtWidgets.QTextEdit(self.centralwidget)
        self.usernameInput.setGeometry(QtCore.QRect(280, 140, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.usernameInput.setFont(font)
        self.usernameInput.setObjectName("usernameInput")
        self.guestButton = QtWidgets.QPushButton(self.centralwidget)
        self.guestButton.setGeometry(QtCore.QRect(450, 220, 200, 100))
        self.guestButton.setObjectName("guestButton")
        self.selectGameButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectGameButton.setGeometry(QtCore.QRect(840, 220, 200, 100))
        self.selectGameButton.setObjectName("selectGameButton")
        self.playersOutput = QtWidgets.QTextEdit(self.centralwidget)
        self.playersOutput.setGeometry(QtCore.QRect(10, 40, 271, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.playersOutput.setFont(font)
        self.playersOutput.setReadOnly(True)
        self.playersOutput.setObjectName("playersOutput")
        self.playersLabel = QtWidgets.QLabel(self.centralwidget)
        self.playersLabel.setGeometry(QtCore.QRect(10, 10, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.playersLabel.setFont(font)
        self.playersLabel.setObjectName("playersLabel")
        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setGeometry(QtCore.QRect(300, 20, 200, 100))
        self.playButton.setObjectName("playButton")
        SelectPlayersDisplay.setCentralWidget(self.centralwidget)

        self.retranslateUi(SelectPlayersDisplay)
        QtCore.QMetaObject.connectSlotsByName(SelectPlayersDisplay)

    def retranslateUi(self, SelectPlayersDisplay):
        _translate = QtCore.QCoreApplication.translate
        SelectPlayersDisplay.setWindowTitle(_translate("SelectPlayersDisplay", "Select Players"))
        self.helpButton.setText(_translate("SelectPlayersDisplay", "Help"))
        self.loadButton.setText(_translate("SelectPlayersDisplay", "Load"))
        self.cancelButton.setText(_translate("SelectPlayersDisplay", "Cancel"))
        self.usernameLabel.setText(_translate("SelectPlayersDisplay", "Username"))
        self.guestButton.setText(_translate("SelectPlayersDisplay", "Guest"))
        self.selectGameButton.setText(_translate("SelectPlayersDisplay", "Select Game"))
        self.playersLabel.setText(_translate("SelectPlayersDisplay", "Players"))
        self.playButton.setText(_translate("SelectPlayersDisplay", "Play"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SelectPlayersDisplay = QtWidgets.QMainWindow()
    ui = Ui_SelectPlayersDisplay()
    ui.setupUi(SelectPlayersDisplay)
    SelectPlayersDisplay.show()
    sys.exit(app.exec_())
