# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_display.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartDisplay(object):
    def setupUi(self, StartDisplay):
        StartDisplay.setObjectName("StartDisplay")
        StartDisplay.resize(800, 400)
        self.centralwidget = QtWidgets.QWidget(StartDisplay)
        self.centralwidget.setObjectName("centralwidget")
        self.createProfileButton = QtWidgets.QPushButton(self.centralwidget)
        self.createProfileButton.setGeometry(QtCore.QRect(150, 150, 200, 100))
        self.createProfileButton.setObjectName("createProfileButton")
        self.helpButton = QtWidgets.QPushButton(self.centralwidget)
        self.helpButton.setGeometry(QtCore.QRect(10, 370, 75, 25))
        self.helpButton.setObjectName("helpButton")
        self.selectGameButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectGameButton.setGeometry(QtCore.QRect(450, 150, 200, 100))
        self.selectGameButton.setObjectName("selectGameButton")
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setGeometry(QtCore.QRect(715, 370, 75, 25))
        self.cancelButton.setObjectName("cancelButton")
        StartDisplay.setCentralWidget(self.centralwidget)

        self.retranslateUi(StartDisplay)
        QtCore.QMetaObject.connectSlotsByName(StartDisplay)

    def retranslateUi(self, StartDisplay):
        _translate = QtCore.QCoreApplication.translate
        StartDisplay.setWindowTitle(_translate("StartDisplay", "Start"))
        self.createProfileButton.setText(_translate("StartDisplay", "Create Profile"))
        self.helpButton.setText(_translate("StartDisplay", "Help"))
        self.selectGameButton.setText(_translate("StartDisplay", "Select Game"))
        self.cancelButton.setText(_translate("StartDisplay", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StartDisplay = QtWidgets.QMainWindow()
    ui = Ui_StartDisplay()
    ui.setupUi(StartDisplay)
    StartDisplay.show()
    sys.exit(app.exec_())
